# Generated by Django 5.2.5 on 2025-08-15 14:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
                ('objects', app.models.AlunoManager()),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(help_text='CPF sem pontos ou traços', max_length=9, unique=True),
        ),
    ]
