# Generated by Django 5.2.5 on 2025-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(help_text='CPF sem pontos ou traços (11 dígitos)', max_length=11, unique=True),
        ),
    ]
